name: UnoFanController
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  libserialport:
    path: ./dart_libserialport
  serial_port_win32: ^2.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0